# AlertManager configuration for Parkrun Helper Organizer
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@parkrun-helper.localhost'
  smtp_auth_username: 'alerts@parkrun-helper.localhost'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  email_configs:
  - to: 'admin@parkrun-helper.localhost'
    subject: 'Parkrun Helper Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}
  webhook_configs:
  - url: 'http://localhost:5001/'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']