# RBAC configuration for Parkrun Helper Organizer
apiVersion: v1
kind: ServiceAccount
metadata:
  name: parkrun-helper-backend
  namespace: parkrun-helper
  labels:
    app: parkrun-helper-organizer
    component: backend
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: parkrun-helper-backend-role
  namespace: parkrun-helper
  labels:
    app: parkrun-helper-organizer
    component: backend
rules:
# Allow reading ConfigMaps and Secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow creating events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# Allow reading pod information for health checks
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: parkrun-helper-backend-rolebinding
  namespace: parkrun-helper
  labels:
    app: parkrun-helper-organizer
    component: backend
subjects:
- kind: ServiceAccount
  name: parkrun-helper-backend
  namespace: parkrun-helper
roleRef:
  kind: Role
  name: parkrun-helper-backend-role
  apiGroup: rbac.authorization.k8s.io