# Secret for Parkrun Helper Organizer sensitive configuration
# Note: In production, secrets should be encrypted and managed securely
apiVersion: v1
kind: Secret
metadata:
  name: parkrun-helper-secrets
  namespace: parkrun-helper
  labels:
    app: parkrun-helper-organizer
    component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # To encode: echo -n "your-secret-value" | base64
  
  # Azure AD Configuration (example values - replace with real ones)
  AZURE_AD_CLIENT_ID: "Y2xpZW50LWlkLWV4YW1wbGU="  # client-id-example
  AZURE_AD_CLIENT_SECRET: "Y2xpZW50LXNlY3JldC1leGFtcGxl"  # client-secret-example
  AZURE_AD_TENANT_ID: "dGVuYW50LWlkLWV4YW1wbGU="  # tenant-id-example
  
  # Cosmos DB Configuration (example values - replace with real ones)
  COSMOS_DB_ENDPOINT: "aHR0cHM6Ly9leGFtcGxlLmRvY3VtZW50cy5henVyZS5jb20="  # https://example.documents.azure.com
  COSMOS_DB_KEY: "cHJpbWFyeS1rZXktZXhhbXBsZQ=="  # primary-key-example
  COSMOS_DB_DATABASE_NAME: "cGFya3J1bi1oZWxwZXI="  # parkrun-helper
  
  # JWT Configuration
  JWT_SECRET: "and0LXNlY3JldC1leGFtcGxl"  # jwt-secret-example
  
  # Additional secrets as needed
  API_KEY: "YXBpLWtleS1leGFtcGxl"  # api-key-example